name: SyncScale.com
description: Website launching soon.
url: 'https://syncscale.com'
baseurl: ''
github: 'https://github.com/syncscale'
permalink: /:title/
markdown: rdiscount
cdn: ''
gems:
  - jekyll-sitemap
  - jekyll-feed
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - CNAME
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
